#!/bin/bash

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=${4:-~/.ssh/id_rsa}

scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"

# Check if the transfer was successful
if [ $? -eq 0 ]; then
    echo "File transferred successfully."
else
    echo "File transfer failed."
fi
