#!/usr/bin/env bash
#comment

filename=/var/run/myscript.pid
sigQuit() {
	rm -rf $filename
	exit
}

#sigIntStop() {
	
#	rm -rf $filename
#	exit
#}

echo "$$" > filename

while :
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo Y U no love me?!" SIGINT
	trap "echo I hate the kill command && sigQuit" SIGTERM
	trap 'sigQuit' SIGQUIT
done
