#!/usr/bin/env bash
#comment

case $1 in
	"start")
		./manage_my_process
		echo $! > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	"stop")
		pkill -f "./manage_my_process"
		rm -rf /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	"restart")
		pkill -f "./manage_my_process"
		rm -rf /var/run/my_process.pid
		./manage_my_process
		echo $! > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
esac
