#!/usr/bin/env bash
#comment

PROCESS_FILE="/tmp/my_process"
PID_FILE="/var/run/my_process.pid"

case "$1" in
    start)
        ./manage_my_process &
        echo $! > "$PID_FILE"
        echo "manage_my_process started"
        ;;
    stop)
        kill "$(cat "$PID_FILE")"
        rm "$PID_FILE"
        echo "manage_my_process stopped"
        ;;
    restart)
        $0 stop
        $0 start
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac
