#!/usr/bin/env bash
# superstition

n=0
while [ $n -lt 20 ]
do
	((n++))
	echo $n
	case $n in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
done
